"""added more columns

Revision ID: 1e824312edc9
Revises: 47225c18c653
Create Date: 2021-01-05 11:07:01.562347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e824312edc9'
down_revision = '47225c18c653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('case_fatality', sa.Float(), nullable=True))
    op.add_column('country', sa.Column('confirmed', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('deaths', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('deaths_per_100k', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'deaths_per_100k')
    op.drop_column('country', 'deaths')
    op.drop_column('country', 'confirmed')
    op.drop_column('country', 'case_fatality')
    # ### end Alembic commands ###
