"""created country model

Revision ID: 47225c18c653
Revises: 601ab05a72e9
Create Date: 2021-01-03 23:44:29.844054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47225c18c653'
down_revision = '601ab05a72e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
