"""empty message

Revision ID: 5737ac874dca
Revises: 
Create Date: 2021-01-27 18:03:05.790982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5737ac874dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('confirmed', sa.String(), nullable=True),
    sa.Column('deaths', sa.String(), nullable=True),
    sa.Column('case_fatality_percentage', sa.String(), nullable=True),
    sa.Column('deaths_per_100k', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selected_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('confirmed', sa.String(), nullable=True),
    sa.Column('deaths', sa.String(), nullable=True),
    sa.Column('case_fatality_percentage', sa.String(), nullable=True),
    sa.Column('deaths_per_100k', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('selected_country')
    op.drop_table('country')
    # ### end Alembic commands ###
