"""reset selected countries

Revision ID: 81e40b6f6c24
Revises: 298f302a9b56
Create Date: 2021-01-05 15:56:20.546124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e40b6f6c24'
down_revision = '298f302a9b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('case_fatality_percentage', sa.Float(), nullable=True),
    sa.Column('deaths_per_100k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selected_country')
    # ### end Alembic commands ###
